- name: install and run nginx
  hosts: web
  become: yes
  tasks:
  - name: install and run n ginx
    ansible.builtin.package:
      name: nginx
      state: present 
  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: start
      enabled: yes 
      