- name: play local variables
  hosts: local
  connection: local
  vars:
    course: "Devops with AWS"
    duration: "140 hrs"
    trainer: "siva kumar"
  tasks:
  - name: print the variables
    ansible.builtin.debug:
      msg: "course is :{{course}},trainer is :{{trainer}}"
  tasks:
  - name: print the variables
    vars:
      course: "ansible"
    ansible.builtin.debug:
      msg: "couse is :{{course}}, trainer is :{{trainer}}"
      