- name: play level variables
  hosts: local
  connection: local
  vars_files:
  - course.yaml
  tasks:
  - name: print the variables 
    ansible.builtin.debug:
      msg: "course is : {{COURSE}},trainer is :{{TRAINER}}"
      
